### ISSUE TITLE
Load more performance issues for large number of records..

### ISSUE THREAD

**Issue by kargoms** [gyrocode/jquery-datatables-pageLoadMore#2]
Hi Team,
I'm using loadmore plugin, i'm facing performance issues to load 500+ records, it takes 7-10 seconds to draw approximately, i have the requirement of serveside implementation of loadmore with checkboxes, also i'm doing some styling based on some conditions at rowCreated so for loading 500+ records itself takes 7-8 seconds. could you please please provide me the sample with better performance of the above scenarios.

**Comment by mpryvkin** [comment]
All examples are available on [this page](https://www.gyrocode.com/articles/jquery-datatables-load-more-button/).

Are you currently using server-side processing mode and seeing a delay of 7-10 seconds?

**Comment by kargoms** [comment]
> All examples are available on [this page](https://www.gyrocode.com/articles/jquery-datatables-load-more-button/).
> 
> Are you currently using server-side processing mode and seeing a delay of 7-10 seconds?

Yes.

**Comment by kargoms** [comment]
Yes currently i'm using server-side processing mode and checkboxes and seeing a delay of 7-10 seconds?

**Comment by mpryvkin** [comment]
Plug-in is very simple, and it shouldn't affect performance. Disable pageLoadMore plug-in and just use server-side processing and see if switching between pages still takes 7-10 seconds.

**Comment by mpryvkin** [comment]
Just pushed out an update (6b5ff8d8c8ba63c5dbfb05b656427acd8a36f75c) fixing issue with processing server-side requests which might have affected the performance and functionality you were describing.
